# Generated by Django 3.0.5 on 2020-04-18 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fingerprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate_X', models.FloatField()),
                ('coordinate_Y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WiFiSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorAppServer.Fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=100)),
                ('x_value', models.FloatField()),
                ('y_value', models.FloatField()),
                ('z_value', models.FloatField()),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorAppServer.Fingerprint')),
            ],
        ),
        migrations.CreateModel(
            name='BluetoothSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beacon_address', models.CharField(max_length=100)),
                ('rssi', models.IntegerField()),
                ('fingerprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indoorAppServer.Fingerprint')),
            ],
        ),
    ]
