# Generated by Django 3.0.5 on 2020-04-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indoorAppServer', '0003_auto_20200425_1657'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bluetoothsensor',
            old_name='beacon_address',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='wifisensor',
            old_name='mac_address',
            new_name='name',
        ),
    ]
