# Generated by Django 3.0.5 on 2020-04-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indoorAppServer', '0004_auto_20200425_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmer',
            name='languages',
        ),
        migrations.AlterField(
            model_name='bluetoothsensor',
            name='fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ble', to='indoorAppServer.Fingerprint'),
        ),
        migrations.AlterField(
            model_name='devicesensor',
            name='fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='indoorAppServer.Fingerprint'),
        ),
        migrations.AlterField(
            model_name='wifisensor',
            name='fingerprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wifi', to='indoorAppServer.Fingerprint'),
        ),
        migrations.DeleteModel(
            name='language',
        ),
        migrations.DeleteModel(
            name='Paradigm',
        ),
        migrations.DeleteModel(
            name='Programmer',
        ),
    ]
