# Generated by Django 3.0.5 on 2020-05-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indoorAppServer', '0005_auto_20200429_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprint',
            name='zone',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
